functionName: sub_80219E8
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/sa3/build/gba/sa3/asm/code_0_2.o
asm: |
  	thumb_func_start sub_80219E8
  sub_80219E8: @ 0x080219E8
  	push {r4, lr}
  	ldr r0, _08021A60 @ =gCurTask
  	ldr r0, [r0]
  	ldrh r1, [r0, #6]
  	movs r0, #0xc0
  	lsls r0, r0, #0x12
  	adds r3, r1, r0
  	movs r2, #0
  	movs r4, #0xff
  _080219FA:
  	lsls r0, r2, #2
  	adds r0, r0, r2
  	lsls r0, r0, #3
  	adds r0, #4
  	adds r1, r3, r0
  	ldrb r0, [r1, #0x1b]
  	orrs r0, r4
  	strb r0, [r1, #0x1b]
  	adds r0, r2, #1
  	lsls r0, r0, #0x18
  	lsrs r2, r0, #0x18
  	cmp r2, #0xb
  	bls _080219FA
  	movs r0, #0xf2
  	lsls r0, r0, #1
  	adds r1, r3, r0
  	movs r0, #0xff
  	strb r0, [r1, #0x1b]
  	movs r0, #0x83
  	lsls r0, r0, #2
  	adds r1, r3, r0
  	movs r0, #1
  	rsbs r0, r0, #0
  	strb r0, [r1, #0x1b]
  	movs r0, #0x8d
  	lsls r0, r0, #2
  	adds r1, r3, r0
  	movs r0, #1
  	rsbs r0, r0, #0
  	strb r0, [r1, #0x1b]
  	movs r0, #0x97
  	lsls r0, r0, #2
  	adds r1, r3, r0
  	movs r0, #1
  	rsbs r0, r0, #0
  	strb r0, [r1, #0x1b]
  	movs r0, #0xa1
  	lsls r0, r0, #2
  	adds r1, r3, r0
  	movs r0, #1
  	rsbs r0, r0, #0
  	strb r0, [r1, #0x1b]
  	movs r0, #0xab
  	lsls r0, r0, #2
  	adds r1, r3, r0
  	movs r0, #1
  	rsbs r0, r0, #0
  	strb r0, [r1, #0x1b]
  	pop {r4}
  	pop {r0}
  	bx r0
  	.align 2, 0
  _08021A60: .4byte gCurTask
