functionName: sub_8087590
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/sa3/build/gba/sa3/asm/code.o
asm: |
  	thumb_func_start sub_8087590
  sub_8087590: @ 0x08087590
  	push {r4, r5, r6, r7, lr}
  	mov r7, r8
  	push {r7}
  	adds r4, r0, #0
  	movs r5, #0
  	ldr r7, _080877E0 @ =gUnknown_080D6114
  	movs r0, #0
  	mov r8, r0
  	movs r6, #0
  _080875A2:
  	lsls r0, r5, #2
  	adds r0, r0, r5
  	lsls r0, r0, #3
  	adds r0, #0x7c
  	adds r1, r4, r0
  	ldr r0, [r4, #0x78]
  	str r0, [r1]
  	ldr r0, [r4, #0x78]
  	movs r2, #0x80
  	lsls r2, r2, #4
  	adds r0, r0, r2
  	str r0, [r4, #0x78]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrh r0, [r0]
  	strh r0, [r1, #0xc]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrb r0, [r0, #2]
  	strb r0, [r1, #0x1a]
  	movs r0, #0xff
  	strb r0, [r1, #0x1b]
  	ldr r0, [r4, #0x18]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x10]
  	ldr r0, [r4, #0x1c]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x12]
  	strh r6, [r1, #0x14]
  	strh r6, [r1, #0xe]
  	strh r6, [r1, #0x16]
  	movs r0, #0x10
  	strb r0, [r1, #0x1c]
  	mov r0, r8
  	strb r0, [r1, #0x1f]
  	movs r0, #0x20
  	str r0, [r1, #8]
  	adds r0, r1, #0
  	bl UpdateSpriteAnimation
  	adds r0, r5, #1
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	cmp r5, #1
  	bls _080875A2
  	movs r5, #0
  	ldr r7, _080877E4 @ =gUnknown_080D6174
  	movs r1, #0
  	mov r8, r1
  	movs r6, #0
  _08087612:
  	lsls r0, r5, #2
  	adds r0, r0, r5
  	lsls r0, r0, #3
  	adds r0, #0xcc
  	adds r1, r4, r0
  	ldr r0, [r4, #0x78]
  	str r0, [r1]
  	ldr r0, [r4, #0x78]
  	movs r2, #0x80
  	lsls r2, r2, #4
  	adds r0, r0, r2
  	str r0, [r4, #0x78]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrh r0, [r0]
  	strh r0, [r1, #0xc]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrb r0, [r0, #2]
  	strb r0, [r1, #0x1a]
  	movs r0, #0xff
  	strb r0, [r1, #0x1b]
  	ldr r0, [r4, #0x20]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x10]
  	ldr r0, [r4, #0x24]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x12]
  	movs r0, #0x40
  	strh r0, [r1, #0x14]
  	strh r6, [r1, #0xe]
  	strh r6, [r1, #0x16]
  	movs r0, #0x10
  	strb r0, [r1, #0x1c]
  	mov r0, r8
  	strb r0, [r1, #0x1f]
  	str r6, [r1, #8]
  	adds r0, r1, #0
  	bl UpdateSpriteAnimation
  	adds r0, r5, #1
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	cmp r5, #1
  	bls _08087612
  	movs r5, #0
  	ldr r7, _080877E8 @ =gUnknown_080D61D4
  	movs r1, #0
  	mov r8, r1
  	movs r6, #0
  _08087682:
  	lsls r0, r5, #2
  	adds r0, r0, r5
  	lsls r0, r0, #3
  	movs r2, #0x8e
  	lsls r2, r2, #1
  	adds r0, r0, r2
  	adds r1, r4, r0
  	ldr r0, [r4, #0x78]
  	str r0, [r1]
  	ldr r0, [r4, #0x78]
  	movs r2, #0x80
  	lsls r2, r2, #4
  	adds r0, r0, r2
  	str r0, [r4, #0x78]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrh r0, [r0]
  	strh r0, [r1, #0xc]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrb r0, [r0, #2]
  	strb r0, [r1, #0x1a]
  	movs r0, #0xff
  	strb r0, [r1, #0x1b]
  	ldr r0, [r4, #0x28]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x10]
  	ldr r0, [r4, #0x2c]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x12]
  	movs r0, #0x80
  	strh r0, [r1, #0x14]
  	strh r6, [r1, #0xe]
  	strh r6, [r1, #0x16]
  	movs r0, #0x10
  	strb r0, [r1, #0x1c]
  	mov r0, r8
  	strb r0, [r1, #0x1f]
  	str r6, [r1, #8]
  	adds r0, r1, #0
  	bl UpdateSpriteAnimation
  	adds r0, r5, #1
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	cmp r5, #1
  	bls _08087682
  	movs r5, #0
  	ldr r7, _080877EC @ =gUnknown_080D6234
  	movs r1, #0
  	mov r8, r1
  	movs r6, #0
  _080876F6:
  	lsls r0, r5, #2
  	adds r0, r0, r5
  	lsls r0, r0, #3
  	movs r2, #0xb6
  	lsls r2, r2, #1
  	adds r0, r0, r2
  	adds r1, r4, r0
  	ldr r0, [r4, #0x78]
  	str r0, [r1]
  	ldr r0, [r4, #0x78]
  	movs r2, #0x80
  	lsls r2, r2, #4
  	adds r0, r0, r2
  	str r0, [r4, #0x78]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrh r0, [r0]
  	strh r0, [r1, #0xc]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrb r0, [r0, #2]
  	strb r0, [r1, #0x1a]
  	movs r0, #0xff
  	strb r0, [r1, #0x1b]
  	ldr r0, [r4, #0x30]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x10]
  	ldr r0, [r4, #0x34]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x12]
  	movs r0, #0xc0
  	strh r0, [r1, #0x14]
  	strh r6, [r1, #0xe]
  	strh r6, [r1, #0x16]
  	movs r0, #0x10
  	strb r0, [r1, #0x1c]
  	mov r0, r8
  	strb r0, [r1, #0x1f]
  	str r6, [r1, #8]
  	adds r0, r1, #0
  	bl UpdateSpriteAnimation
  	adds r0, r5, #1
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	cmp r5, #1
  	bls _080876F6
  	movs r5, #0
  	ldr r7, _080877F0 @ =gUnknown_080D6354
  	movs r1, #0
  	mov r8, r1
  	movs r6, #0
  _0808776A:
  	lsls r0, r5, #2
  	adds r0, r0, r5
  	lsls r0, r0, #3
  	movs r2, #0x97
  	lsls r2, r2, #2
  	adds r0, r0, r2
  	adds r1, r4, r0
  	ldr r0, [r4, #0x78]
  	str r0, [r1]
  	ldr r0, [r4, #0x78]
  	movs r2, #0x80
  	lsls r2, r2, #4
  	adds r0, r0, r2
  	str r0, [r4, #0x78]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrh r0, [r0]
  	strh r0, [r1, #0xc]
  	ldrb r0, [r4]
  	lsls r0, r0, #1
  	adds r0, r5, r0
  	lsls r0, r0, #3
  	adds r0, r0, r7
  	ldrb r0, [r0, #2]
  	strb r0, [r1, #0x1a]
  	movs r0, #0xff
  	strb r0, [r1, #0x1b]
  	ldr r0, [r4, #0x48]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x10]
  	ldr r0, [r4, #0x4c]
  	asrs r0, r0, #8
  	strh r0, [r1, #0x12]
  	movs r0, #0xc0
  	strh r0, [r1, #0x14]
  	strh r6, [r1, #0xe]
  	strh r6, [r1, #0x16]
  	movs r0, #0x10
  	strb r0, [r1, #0x1c]
  	mov r0, r8
  	strb r0, [r1, #0x1f]
  	str r6, [r1, #8]
  	adds r0, r1, #0
  	bl UpdateSpriteAnimation
  	adds r0, r5, #1
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	cmp r5, #1
  	bls _0808776A
  	pop {r3}
  	mov r8, r3
  	pop {r4, r5, r6, r7}
  	pop {r0}
  	bx r0
  	.align 2, 0
  _080877E0: .4byte gUnknown_080D6114
  _080877E4: .4byte gUnknown_080D6174
  _080877E8: .4byte gUnknown_080D61D4
  _080877EC: .4byte gUnknown_080D6234
  _080877F0: .4byte gUnknown_080D6354
