functionName: sub_8068C38
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/sa3/build/gba/sa3/asm/code.o
asm: |
  	thumb_func_start sub_8068C38
  sub_8068C38: @ 0x08068C38
  	push {r4, r5, r6, lr}
  	ldr r0, _08068CBC @ =gCurTask
  	ldr r0, [r0]
  	ldrh r1, [r0, #6]
  	movs r0, #0xc0
  	lsls r0, r0, #0x12
  	adds r4, r1, r0
  	adds r0, #0xf0
  	adds r6, r1, r0
  	ldrh r0, [r4, #0x32]
  	adds r0, #1
  	strh r0, [r4, #0x32]
  	adds r0, r4, #0
  	bl sub_8069814
  	adds r0, r4, #0
  	bl sub_8069360
  	adds r0, r4, #0
  	bl sub_806A894
  	ldr r0, [r4, #0x50]
  	bl sub_8068E5C
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	ldr r0, [r4, #0x54]
  	bl sub_8068E5C
  	adds r0, r5, r0
  	lsls r0, r0, #0x18
  	lsrs r5, r0, #0x18
  	ldrb r1, [r4, #0xd]
  	movs r0, #0xd
  	ldrsb r0, [r4, r0]
  	cmp r0, #0
  	beq _08068C96
  	subs r0, r1, #1
  	strb r0, [r4, #0xd]
  	lsls r0, r0, #0x18
  	cmp r0, #0
  	bne _08068C96
  	movs r0, #0x97
  	lsls r0, r0, #3
  	strh r0, [r6, #0xc]
  	movs r0, #0
  	strb r0, [r6, #0x1a]
  _08068C96:
  	cmp r5, #0
  	beq _08068CA0
  	adds r0, r4, #0
  	bl sub_806A5DC
  _08068CA0:
  	ldrb r0, [r4, #0xc]
  	cmp r0, #0
  	bne _08068CDE
  	ldr r1, _08068CC0 @ =gStageData
  	ldrb r0, [r1, #3]
  	cmp r0, #5
  	bne _08068CD0
  	ldrb r0, [r1, #6]
  	cmp r0, #0
  	beq _08068CC8
  	ldr r0, _08068CBC @ =gCurTask
  	ldr r1, [r0]
  	ldr r0, _08068CC4 @ =sub_806A7A4
  	b _08068CDC
  	.align 2, 0
  _08068CBC: .4byte gCurTask
  _08068CC0: .4byte gStageData
  _08068CC4: .4byte sub_806A7A4
  _08068CC8:
  	movs r0, #1
  	movs r1, #0
  	bl sub_8027674
  _08068CD0:
  	adds r0, r4, #0
  	bl sub_806A818
  	ldr r0, _08068CF8 @ =gCurTask
  	ldr r1, [r0]
  	ldr r0, _08068CFC @ =sub_806A760
  _08068CDC:
  	str r0, [r1, #8]
  _08068CDE:
  	adds r0, r4, #0
  	bl sub_8069578
  	adds r0, r4, #0
  	bl sub_806A854
  	adds r0, r4, #0
  	bl sub_806A898
  	pop {r4, r5, r6}
  	pop {r0}
  	bx r0
  	.align 2, 0
  _08068CF8: .4byte gCurTask
  _08068CFC: .4byte sub_806A760
