functionName: sub_80A3EAC
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/sa3/build/gba/sa3/asm/code_2.o
asm: |
  	thumb_func_start sub_80A3EAC
  sub_80A3EAC: @ 0x080A3EAC
  	push {r4, r5, lr}
  	adds r5, r0, #0
  	movs r4, #0
  _080A3EB2:
  	lsls r0, r4, #2
  	adds r0, r0, r4
  	lsls r0, r0, #3
  	adds r0, #0xd4
  	adds r0, r5, r0
  	ldr r1, [r5, #0x1c]
  	asrs r1, r1, #8
  	strh r1, [r0, #0x10]
  	ldr r1, [r5, #0x20]
  	asrs r1, r1, #8
  	strh r1, [r0, #0x12]
  	bl DisplaySprite
  	adds r0, r4, #1
  	lsls r0, r0, #0x18
  	lsrs r4, r0, #0x18
  	cmp r4, #1
  	bls _080A3EB2
  	pop {r4, r5}
  	pop {r0}
  	bx r0
