functionName: sub_80ACD10
targetObjectPath: /Users/macabeus/ApenasMeu/decompiler/sa3/build/gba/sa3/asm/code_2.o
asm: |
  	thumb_func_start sub_80ACD10
  sub_80ACD10: @ 0x080ACD10
  	push {r4, r5, r6, r7, lr}
  	mov r7, sl
  	mov r6, sb
  	mov r5, r8
  	push {r5, r6, r7}
  	adds r7, r0, #0
  	movs r0, #0x36
  	bl VramMalloc
  	adds r6, r0, #0
  	adds r0, r7, #0
  	adds r0, #0x5c
  	str r6, [r7, #0x5c]
  	ldr r4, _080ACDB4 @ =gUnknown_080DBA94
  	ldr r1, [r4, #0xc]
  	lsls r1, r1, #5
  	adds r6, r6, r1
  	ldrh r1, [r4, #8]
  	movs r2, #0
  	mov sl, r2
  	movs r5, #0
  	strh r1, [r0, #0xc]
  	ldrb r1, [r4, #0xa]
  	strb r1, [r0, #0x1a]
  	movs r1, #0xff
  	strb r1, [r0, #0x1b]
  	ldr r1, [r7, #0x20]
  	asrs r1, r1, #8
  	strh r1, [r0, #0x10]
  	ldr r1, [r7, #0x24]
  	asrs r1, r1, #8
  	strh r1, [r0, #0x12]
  	movs r1, #0xa0
  	lsls r1, r1, #1
  	mov sb, r1
  	mov r2, sb
  	strh r2, [r0, #0x14]
  	strh r5, [r0, #0xe]
  	strh r5, [r0, #0x16]
  	movs r1, #0x10
  	mov r8, r1
  	mov r2, r8
  	strb r2, [r0, #0x1c]
  	mov r1, sl
  	strb r1, [r0, #0x1f]
  	str r5, [r0, #8]
  	bl UpdateSpriteAnimation
  	adds r0, r7, #0
  	adds r0, #0x84
  	str r6, [r0]
  	ldrh r1, [r4]
  	strh r1, [r0, #0xc]
  	ldrb r1, [r4, #2]
  	strb r1, [r0, #0x1a]
  	movs r1, #1
  	rsbs r1, r1, #0
  	strb r1, [r0, #0x1b]
  	ldr r1, [r7, #0x20]
  	asrs r1, r1, #8
  	strh r1, [r0, #0x10]
  	ldr r1, [r7, #0x24]
  	asrs r1, r1, #8
  	strh r1, [r0, #0x12]
  	mov r2, sb
  	strh r2, [r0, #0x14]
  	strh r5, [r0, #0xe]
  	strh r5, [r0, #0x16]
  	mov r1, r8
  	strb r1, [r0, #0x1c]
  	mov r2, sl
  	strb r2, [r0, #0x1f]
  	str r5, [r0, #8]
  	bl UpdateSpriteAnimation
  	pop {r3, r4, r5}
  	mov r8, r3
  	mov sb, r4
  	mov sl, r5
  	pop {r4, r5, r6, r7}
  	pop {r0}
  	bx r0
  	.align 2, 0
  _080ACDB4: .4byte gUnknown_080DBA94
